version: '3'

services:
  db:
    build: ./mariadb/
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
    - wordpress_db:/var/lib/mysql
    networks:
    - app-network
    ports:
    - "3306:3306"
  wordpress:
    depends_on:
    - db
    build : ./wordpress/
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    volumes:
    - wordpress:/var/www/html
    networks:
    - app-network
    ports:
    - "9000:9000"
  webserver:
    depends_on: 
    - wordpress
    build: ./nginx/
    container_name: nginx
    restart: unless-stopped
    ports:
    - "443:443"
    networks:
      - app-network
volumes:
  wordpress_db:
  wordpress:
networks:
  app-network:
   driver: bridge
