version: '3'

services:
  db:
    build: /requirements/mariadb/
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
    networks:
  wordpress:
    depends_on:
    - db
    build : /requirements/wordpress/
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    volumes:
    networks:
  webserver:
    depends_on: wordpress
    build: /requirements/nginx/
    container_name: nginx
    restart: unless-stopped
    ports:
    - "443:443"
volumes:
    -
networks:
  -
