version: '3'

services:
  db:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
     - wordpress_db:/var/lib/mysql/
    networks:
     - app-network
  wordpress:
    depends_on:
     - db
    build : ./requirements/wordpress/
    container_name: wordpress
    restart: unless-stopped
    volumes:
     - wordpress:/var/www/html/wordpress
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    env_file: .env
    networks:
     - app-network
  webserver:
    depends_on: 
     - wordpress
    build: ./requirements/nginx/
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    volumes:
     - wordpress:/var/www/html/wordpress
    ports:
     - "443:443"
    networks:
      - app-network
volumes:
  wordpress_db:
   driver: local
   driver_opts:
    type : none
    o : bind
    device: "${PWD}/requirements/mariadb/tools/"
  wordpress:
   driver: local
   driver_opts:
    type : none
    o : bind
    device: ".${PWD}/requirements/wordpress/tools/"
networks:
  app-network:
   driver: bridge