version: '3'

services:
  mariadb:
    build: 
     context: ./requirements/mariadb/
     args:
      - MYSQL_ROOT_PASSWORD=CmWp%13
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=CmWp%13
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
     - wordpress_db:/var/lib/mysql/
    networks:
     - app-network
  wordpress:
    depends_on:
     - mariadb
    build :
     context: ./requirements/wordpress/
     args:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=CmWp%13
      - WORDPRESS_USER_NAME=cel-mhan
      - ADMIN_USER=wordpress
      - WORDPRESS_USER_EMAIL=cel-mhan@gmail.com
      - ADMIN_EMAIL=wordpress@gmail.com
      - WORDPRESS_PASSWORD=CmWp%13
    container_name: wordpress
    restart: unless-stopped
    volumes:
     - wordpress:/var/www/html/
    env_file: .env
    networks:
     - app-network
  webserver:
    depends_on: 
     - wordpress
    build: ./requirements/nginx/
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    volumes:
     - wordpress:/var/www/html/
    ports:
     - "443:443"
    networks:
      - app-network
volumes:
  wordpress_db:
   driver: local
   driver_opts:
    type : none
    o : bind
    device: "/home/cel-mhan/data/db"
  wordpress:
   driver: local
   driver_opts:
    type : none
    o : bind
    device: "/home/cel-mhan/data/wp"
networks:
  app-network:
   driver: bridge